"""initial schema

Revision ID: b44b164714d5
Revises: 
Create Date: 2026-09-11 01:27:27.170029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b44b164714d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('serial', sa.String(length=200), nullable=False),
    sa.Column('avd_name', sa.String(length=200), nullable=True),
    sa.Column('android_api', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=20), nullable=True),
    sa.Column('package_id', sa.String(length=300), nullable=True),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('capability_report_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_profiles_serial'), ['serial'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('root_path', sa.String(length=1024), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('active_revision_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['active_revision_id'], ['revisions.id'], name='fk_projects_active_revision', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_slug'), ['slug'], unique=True)

    op.create_table('assets',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('origin', sa.String(length=30), nullable=False),
    sa.Column('relative_path', sa.String(length=1024), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('duration_us', sa.Integer(), nullable=True),
    sa.Column('timebase_json', sa.JSON(), nullable=False),
    sa.Column('dimensions_json', sa.JSON(), nullable=False),
    sa.Column('audio_info_json', sa.JSON(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assets_sha256'), ['sha256'], unique=False)

    op.create_table('briefs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=500), nullable=False),
    sa.Column('single_message', sa.String(length=500), nullable=False),
    sa.Column('objective', sa.String(length=200), nullable=False),
    sa.Column('style_id', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('target_frames', sa.Integer(), nullable=False),
    sa.Column('fps_num', sa.Integer(), nullable=False),
    sa.Column('fps_den', sa.Integer(), nullable=False),
    sa.Column('placement_id', sa.String(length=100), nullable=False),
    sa.Column('budget_microusd', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefs_project_id'), ['project_id'], unique=False)

    op.create_table('character_profiles',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('wardrobe', sa.String(length=1000), nullable=True),
    sa.Column('location', sa.String(length=1000), nullable=True),
    sa.Column('voice_profile_id', sa.String(length=200), nullable=True),
    sa.Column('reference_asset_ids_json', sa.JSON(), nullable=False),
    sa.Column('continuity_notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_character_profiles_project_id'), ['project_id'], unique=False)

    op.create_table('game_profiles',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('device_profile_id', sa.String(), nullable=False),
    sa.Column('mechanic_summary', sa.String(length=4000), nullable=False),
    sa.Column('navigation_json', sa.JSON(), nullable=False),
    sa.Column('state_signals_json', sa.JSON(), nullable=False),
    sa.Column('supported_actions_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_profiles_project_id'), ['project_id'], unique=False)

    op.create_table('asset_rights',
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('license_note', sa.String(length=1000), nullable=True),
    sa.Column('user_provided', sa.Boolean(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('asset_rights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_rights_asset_id'), ['asset_id'], unique=False)

    op.create_table('brand_profiles',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('verified_claims_json', sa.JSON(), nullable=False),
    sa.Column('forbidden_claims_json', sa.JSON(), nullable=False),
    sa.Column('colors_json', sa.JSON(), nullable=False),
    sa.Column('logo_asset_id', sa.String(), nullable=True),
    sa.Column('cta', sa.String(length=200), nullable=True),
    sa.Column('destination_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['logo_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_brand_profiles_project_id'), ['project_id'], unique=False)

    op.create_table('checkpoints',
    sa.Column('game_profile_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('snapshot_ref', sa.String(length=300), nullable=False),
    sa.Column('app_version', sa.String(length=100), nullable=True),
    sa.Column('emulator_version', sa.String(length=100), nullable=True),
    sa.Column('state_evidence_asset_id', sa.String(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_profile_id'], ['game_profiles.id'], ),
    sa.ForeignKeyConstraint(['state_evidence_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkpoints_game_profile_id'), ['game_profile_id'], unique=False)

    op.create_table('concepts',
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('angle', sa.String(length=200), nullable=False),
    sa.Column('hook', sa.String(length=1000), nullable=False),
    sa.Column('rationale', sa.String(length=2000), nullable=False),
    sa.Column('claim_refs_json', sa.JSON(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_brief_id'), ['brief_id'], unique=False)

    op.create_table('revisions',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('timeline_json', sa.JSON(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_summary', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_project_id'), ['project_id'], unique=False)

    op.create_table('exports',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('placement_profile_version', sa.String(length=50), nullable=False),
    sa.Column('file_asset_id', sa.String(), nullable=False),
    sa.Column('manifest_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exports_project_id'), ['project_id'], unique=False)

    op.create_table('jobs',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('revision_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('lease_owner', sa.String(length=100), nullable=True),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'idempotency_key', name='uq_job_idempotency')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_state'), ['state'], unique=False)

    op.create_table('qa_reports',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('checks_json', sa.JSON(), nullable=False),
    sa.Column('reviewer_model', sa.String(length=200), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('human_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qa_reports_revision_id'), ['revision_id'], unique=False)

    op.create_table('shots',
    sa.Column('revision_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('desired_event', sa.String(length=200), nullable=True),
    sa.Column('start_state_json', sa.JSON(), nullable=False),
    sa.Column('success_predicate_json', sa.JSON(), nullable=False),
    sa.Column('action_constraints_json', sa.JSON(), nullable=False),
    sa.Column('target_frames', sa.Integer(), nullable=False),
    sa.Column('handles_frames', sa.JSON(), nullable=False),
    sa.Column('character_id', sa.String(), nullable=True),
    sa.Column('generation_prompt', sa.String(length=4000), nullable=True),
    sa.Column('voice_text', sa.String(length=2000), nullable=True),
    sa.Column('caption_text', sa.String(length=500), nullable=True),
    sa.Column('selected_take_id', sa.String(), nullable=True),
    sa.Column('locks_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character_profiles.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ),
    sa.ForeignKeyConstraint(['selected_take_id'], ['takes.id'], name='fk_shots_selected_take', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_shots_revision_id'), ['revision_id'], unique=False)

    op.create_table('device_sessions',
    sa.Column('device_profile_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('owner_token', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_sessions_device_profile_id'), ['device_profile_id'], unique=False)

    op.create_table('event_log',
    sa.Column('sequence', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('sequence')
    )
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_log_project_id'), ['project_id'], unique=False)

    op.create_table('performance_notes',
    sa.Column('export_id', sa.String(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=True),
    sa.Column('views_definition', sa.String(length=200), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('clicks', sa.Integer(), nullable=True),
    sa.Column('installs', sa.Integer(), nullable=True),
    sa.Column('spend_microusd', sa.Integer(), nullable=True),
    sa.Column('date_range', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['export_id'], ['exports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('performance_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_performance_notes_export_id'), ['export_id'], unique=False)

    op.create_table('provider_requests',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=200), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('remote_id', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=30), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('catalog_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_microusd', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('provider_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_provider_requests_job_id'), ['job_id'], unique=False)

    op.create_table('takes',
    sa.Column('shot_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('in_us', sa.Integer(), nullable=False),
    sa.Column('out_us', sa.Integer(), nullable=False),
    sa.Column('event_evidence_json', sa.JSON(), nullable=False),
    sa.Column('quality_json', sa.JSON(), nullable=False),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('takes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_takes_shot_id'), ['shot_id'], unique=False)

    op.create_table('budget_entries',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('entry_type', sa.String(length=30), nullable=False),
    sa.Column('amount_microusd', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('provider_request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['provider_request_id'], ['provider_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_budget_entries_project_id'), ['project_id'], unique=False)

    op.create_table('device_events',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('capture_id', sa.String(length=100), nullable=True),
    sa.Column('monotonic_ns', sa.Integer(), nullable=False),
    sa.Column('media_pts_us', sa.Integer(), nullable=True),
    sa.Column('mapping_uncertainty_us', sa.Integer(), nullable=True),
    sa.Column('action_json', sa.JSON(), nullable=False),
    sa.Column('observed_state_json', sa.JSON(), nullable=False),
    sa.Column('evidence_asset_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['device_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_events_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_events_session_id'))

    op.drop_table('device_events')
    with op.batch_alter_table('budget_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_entries_project_id'))

    op.drop_table('budget_entries')
    with op.batch_alter_table('takes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_takes_shot_id'))

    op.drop_table('takes')
    with op.batch_alter_table('provider_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_provider_requests_job_id'))

    op.drop_table('provider_requests')
    with op.batch_alter_table('performance_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_performance_notes_export_id'))

    op.drop_table('performance_notes')
    with op.batch_alter_table('event_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_log_project_id'))

    op.drop_table('event_log')
    with op.batch_alter_table('device_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_sessions_device_profile_id'))

    op.drop_table('device_sessions')
    with op.batch_alter_table('shots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shots_revision_id'))

    op.drop_table('shots')
    with op.batch_alter_table('qa_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_reports_revision_id'))

    op.drop_table('qa_reports')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_state'))
        batch_op.drop_index(batch_op.f('ix_jobs_project_id'))

    op.drop_table('jobs')
    with op.batch_alter_table('exports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exports_project_id'))

    op.drop_table('exports')
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_project_id'))

    op.drop_table('revisions')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_brief_id'))

    op.drop_table('concepts')
    with op.batch_alter_table('checkpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkpoints_game_profile_id'))

    op.drop_table('checkpoints')
    with op.batch_alter_table('brand_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_brand_profiles_project_id'))

    op.drop_table('brand_profiles')
    with op.batch_alter_table('asset_rights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_rights_asset_id'))

    op.drop_table('asset_rights')
    with op.batch_alter_table('game_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_profiles_project_id'))

    op.drop_table('game_profiles')
    with op.batch_alter_table('character_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_character_profiles_project_id'))

    op.drop_table('character_profiles')
    with op.batch_alter_table('briefs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefs_project_id'))

    op.drop_table('briefs')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_sha256'))
        batch_op.drop_index(batch_op.f('ix_assets_project_id'))

    op.drop_table('assets')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_slug'))

    op.drop_table('projects')
    with op.batch_alter_table('device_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_profiles_serial'))

    op.drop_table('device_profiles')
    # ### end Alembic commands ###
